Correctif Gn
messagerie-melanie2/ORM-M2 pull request #5
Opened 2022-11-09 12:43 UTC by SamKer

2 bugs "apparent":
- outofoffice:

la sauvegarde écrase l'enregitsrement de l'attribut mceVacation dans le ldap pour les absences..

le correctif récupère la liste avant sauvegarde pour conserver les anciens enregistrements

- readItemConfiguration:

en accord avec la doc pour la gestion des items, l'explosion de la clé dans la conf"items" n'est pas suffisante..

2022-11-09 12:43 UTC, SamKer commented on src/Api/Gn/User.php
> +    const LOAD_ATTRIBUTES = ['fullname', 'uid', 'name', 'email', 'email_list', 'email_send', 'email_send_list', 'server_routage', 'shares', 'type','mcemailroutingaddress','outofoffices'];
ajout de champs par défauts pour la récupération d'infos

2022-11-09 12:44 UTC, SamKer commented on src/Api/Gn/User.php
> +    "mcemailroutingaddress"   => [MappingMce::name => 'mcemailroutingaddress', MappingMce::type => MappingMce::arrayLdap], // routegemceadrressmail host
mapping particulier pour mcevacation...

2022-11-09 12:45 UTC, SamKer commented on src/Api/Gn/User.php
> +        $right = $share->type;
le switch case effectue la même chose systématiquement donc inutile"

2022-11-09 12:45 UTC, SamKer commented on src/Api/Gn/User.php
> -        switch (\strtoupper($right)) {
switch case inutile

2022-11-09 12:45 UTC, SamKer commented on src/Api/Gn/User.php
> +    $reponses = $this->objectmelanie->outofoffices??[];
récupération de la liste mceVacation avant écrasement. pour ne pas perdre de données.

2022-11-09 12:47 UTC, SamKer commented on src/Objects/UserMelanie.php
> -        $parts = explode('.', $itemName);
en accord avec la doc:

la recherche d'un item "webmail.mon_compte.gestionnaireabsence" doit se faire dans l'ordre sur
- webmail.mon_compte.gestionnaireabsence
- webmail.mon_compte
- webmail

hors il se  faisait auparavant en:
- webmail
- mon_compte
- gestionnaireabsence

2022-11-09 13:45 UTC, tpayen requested changes

2022-11-09 13:45 UTC, tpayen commented on src/Api/Gn/User.php
> +    $reponses = $this->objectmelanie->outofoffices??[];
En principe setMapOutofoffices() écrase toutes les entrées existantes de outofoffice c'est donc au client d'envoyer toutes les absences d'un seul coup (c'est ce que fait le webmail). Sinon effectivement les anciennes sont écrasées.

Mais si je comprends bien votre besoin serait plutôt d'ajouter une méthode "addOutofoffice()" dans l'objet User pour que vous puissiez ajouter de nouvelles absences sans toucher aux anciennes.

Parce que là j'ai l'impression qu'avec cette modification, dés que l'absence sera enregistrée depuis le webmail elles vont toutes être doublées.

2022-11-09 13:45 UTC, tpayen commented on src/Objects/UserMelanie.php
> -        $parts = explode('.', $itemName);
Ok effectivement, je regarde ça en détails

2022-11-14 11:03 UTC, tpayen commented on src/Api/Gn/User.php
> +    "displayname"   => 'displayname',
Pour le mapping du champ displayName on met plutôt "name" comme nom de champ au MTE, je pense de mémoire que "name" est utilisé  à certains endroit du code (chez vous c'est actuellement mappé sur le cn) je ne sais pas si ça te va donc de mettre "name" pour ce champ ?

2022-11-14 11:03 UTC, tpayen commented on src/Api/Gn/User.php
> +    "givenname"   => 'givenname',
Pour "givenName" on a le champ "firstname" et le champ "lastname" pour "sn". Pareil, à voir si ça te convient ?

2022-11-14 13:20 UTC, SamKer commented on src/Api/Gn/User.php
> +    "givenname"   => 'givenname', //todo usage firstname => givenname, (lastname =>sn), tester usage , où en ai je eu besoin??
je laisse temporairement mais je prend bien en compte ta suggestion, j'ai juste peur d'un débordement  car je ne sais plus pourquoi on a utilisé ces champs.. dès que je teste je met en place les suggestions.

2022-11-14 13:24 UTC, SamKer commented
j'ai fait roollback sur outofoffice.

je laisse le mapping particulier pour l'iunstant, je voudrais tester la modif conseillé avant de le faire..

le restant est ok.

2022-11-14 13:48 UTC, merged